name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # Installation des dépendances
    - name: Install dependencies
      run: npm ci
    
    - name: Retrieve Xray Token
      id: get-xray-token
      run: node get-xray-token.js
      env:
        XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
        XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}

    - name: Set XRAY_API_TOKEN environment variable
      run: echo "XRAY_API_TOKEN=${{ steps.get-xray-token.outputs.XRAY_API_TOKEN }}" >> $GITHUB_ENV
    
    # Installation des navigateurs
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    # Lancement des tests que sur chrome  
    - name: Run Playwright tests 
      run: npx playwright test tests/autoExercisePOM_2.spec.ts --project chromium
    
    - name: Transform report for Xray
      run: node transform-report.js

    - name: Send results to Xray
      run: node send-results.js
      env:
        XRAY_API_TOKEN: ${{ env.XRAY_API_TOKEN }}  # Utiliser le token dans l'étape d'envoi des résultats
    
    # Génération du rapport Allure
    - name: Generate Allure Report
      run: npm run allure:generate
    
    # Deploy report to GitHub Pages
    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
    
  notifications:
    needs: test
    runs-on: ubuntu-latest
    steps:

    # Step 1: Send Slack notification
    - name: Send Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: repo,author,eventName,workflow,job,took
        custom_payload: |
          {
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              "text": "Playwright Tests completed. Check the Allure report: <https://fndiaye2015.github.io/playwright-demo/|Allure Report>"
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  
    

    
    
    